import { Call } from "./types";

export const importedReferenceCalls: Call[] = [
  {
    id: "ref_call_essex_20260929_001",
    datetime_str: "Sep 29, 2026, 09:18 AM",
    duration_seconds: 184,
    duration_str: "3m 04s",
    cost: "GBP 1.53",
    caller_phone: "+44 7700 900618",
    destination_phone: "+44 1245 982115",
    contact_name: "Sarah Whitmore",
    agent_name: "Essex Heating Inbound",
    direction: "Inbound",
    status: "Answered",
    end_reason: "Agent Hung Up",
    outcome: "Booking Confirmed",
    is_favourite: true,
    call_status: "Completed",
    call_success: "Success",
    user_sentiment: "Positive",
    disconnection_reason: "Completed Normally",
    latency: "728ms",
    recording_url: "/recordings/reference-call-001.wav",
    public_log_url: "https://voiceagent.webuildtrades.com/calls/ref_call_essex_20260929_001",
    source_portal_url: "https://voiceagent.webuildtrades.com/dashboard",
    custom_analysis: {
      caller_name: "Sarah Whitmore",
      email: "sarah.whitmore@example.co.uk",
      postcode: "CM2 8RX",
      property_address: "11 Springfield Road, Chelmsford",
      service_job_type: "Boiler service",
      boiler_type: "Worcester Bosch Greenstar",
      issue_reported: "Annual service request with low pressure question",
      emergency_status: "No",
      fuel_type: "Natural Gas",
      timeframe: "This week",
      caller_type: "Homeowner",
      quote_form_status: "Not required",
    },
    summary: "Caller requested an annual boiler service and asked about low pressure. The agent confirmed postcode, captured email, checked availability and booked the service visit for Thursday morning.",
    transcript: [
      { speaker: "agent", text: "Good morning, Essex Heating. Olivia speaking. How can I help today?", timestamp: "0" },
      { speaker: "user", text: "I need to book a boiler service, and the pressure has been dropping a little.", timestamp: "7" },
      { speaker: "agent", text: "I can help with that. Can I confirm the postcode for the property?", timestamp: "18" },
      { speaker: "user", text: "Yes, it is CM2 8RX.", timestamp: "25" },
      { speaker: "agent", text: "Thank you. I have a Thursday morning appointment available. Would that work?", timestamp: "42" },
      { speaker: "user", text: "Yes, Thursday morning is perfect.", timestamp: "51" },
      { speaker: "agent", text: "Great, I have booked that and added the low pressure note for the engineer.", timestamp: "63" },
    ],
    review_status: "Reviewed - Good",
    feedback_comment: "Good qualification, clear appointment confirmation and useful engineer note.",
  },
  {
    id: "ref_call_boiler_20260929_002",
    datetime_str: "Sep 29, 2026, 10:06 AM",
    duration_seconds: 136,
    duration_str: "2m 16s",
    cost: "GBP 1.13",
    caller_phone: "+44 7700 900741",
    destination_phone: "+44 1245 982001",
    contact_name: "Imran Patel",
    agent_name: "Boiler Sure - Inbound",
    direction: "Inbound",
    status: "Answered",
    end_reason: "User Hung Up",
    outcome: "Emergency Dispatch",
    is_favourite: true,
    call_status: "Completed",
    call_success: "Success",
    user_sentiment: "Negative",
    disconnection_reason: "User Hung Up",
    latency: "762ms",
    recording_url: "/recordings/reference-call-002.wav",
    public_log_url: "https://voiceagent.webuildtrades.com/calls/ref_call_boiler_20260929_002",
    source_portal_url: "https://voiceagent.webuildtrades.com/dashboard",
    custom_analysis: {
      caller_name: "Imran Patel",
      email: "imran.patel@example.co.uk",
      postcode: "SS1 2BG",
      property_address: "6 Queensway, Southend-on-Sea",
      service_job_type: "Emergency boiler repair",
      boiler_type: "Ideal Logic",
      issue_reported: "No heating and error code showing",
      emergency_status: "Yes",
      fuel_type: "Natural Gas",
      timeframe: "Immediate",
      caller_type: "Homeowner",
      quote_form_status: "Not required",
    },
    summary: "Caller had no heating and an Ideal Logic error code. The agent treated it as urgent, captured contact details, advised basic safety checks and escalated for same-day engineer dispatch.",
    transcript: [
      { speaker: "agent", text: "Boiler Sure emergency line, Olivia speaking. Are you safe at the property?", timestamp: "0" },
      { speaker: "user", text: "Yes, but we have no heating and the boiler has an error code.", timestamp: "6" },
      { speaker: "agent", text: "I understand. Is there any smell of gas or visible leak?", timestamp: "15" },
      { speaker: "user", text: "No smell of gas, just no heating.", timestamp: "22" },
      { speaker: "agent", text: "Thank you. I will mark this urgent and pass the error code to the engineer.", timestamp: "35" },
      { speaker: "user", text: "Please send someone today if possible.", timestamp: "47" },
      { speaker: "agent", text: "I have escalated this for same-day dispatch and added your postcode SS1 2BG.", timestamp: "58" },
    ],
    review_status: "Needs Improvement",
    feedback_comment: "Good urgency handling; add a stronger disclaimer before any boiler troubleshooting.",
  },
  {
    id: "ref_call_roofing_20260929_003",
    datetime_str: "Sep 29, 2026, 11:42 AM",
    duration_seconds: 219,
    duration_str: "3m 39s",
    cost: "GBP 1.82",
    caller_phone: "+44 7700 900864",
    destination_phone: "+44 1273 884020",
    contact_name: "Megan Price",
    agent_name: "Roofline Repairs Setter",
    direction: "Outbound",
    status: "Answered",
    end_reason: "Agent Hung Up",
    outcome: "Photo Link Sent",
    is_favourite: false,
    call_status: "Completed",
    call_success: "Success",
    user_sentiment: "Neutral",
    disconnection_reason: "Completed Normally",
    latency: "691ms",
    recording_url: "/recordings/reference-call-003.wav",
    public_log_url: "https://voiceagent.webuildtrades.com/calls/ref_call_roofing_20260929_003",
    source_portal_url: "https://voiceagent.webuildtrades.com/dashboard",
    custom_analysis: {
      caller_name: "Megan Price",
      email: "megan.price@example.co.uk",
      postcode: "BN1 5AD",
      property_address: "29 Ditchling Road, Brighton",
      service_job_type: "Roof repair estimate",
      issue_reported: "Damp patch after rain, possible flat roof leak",
      emergency_status: "No",
      timeframe: "This week",
      caller_type: "Landlord",
      quote_form_status: "Photo upload link sent",
    },
    summary: "Outbound follow-up for a roof repair enquiry. The agent confirmed the damp patch issue, captured the property postcode and sent a photo upload link before survey scheduling.",
    transcript: [
      { speaker: "agent", text: "Hi Megan, this is the Roofline Repairs assistant following up on your enquiry.", timestamp: "0" },
      { speaker: "user", text: "Yes, there is a damp patch after rain and I think it may be the flat roof.", timestamp: "8" },
      { speaker: "agent", text: "Thanks. I can send a photo upload link so the surveyor can review it before booking.", timestamp: "20" },
      { speaker: "user", text: "That would be helpful. The postcode is BN1 5AD.", timestamp: "31" },
      { speaker: "agent", text: "Perfect, I have sent the link and added the postcode to your record.", timestamp: "45" },
    ],
    review_status: "Not Reviewed",
    feedback_comment: "",
  },
];
